spring:
  application:
    name: RepoLens AI
  
  datasource:
    url: jdbc:h2:mem:repolens
    driver-class-name: org.h2.Driver
    username: sa
    password:
  
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: true
  
  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8080

# Application Configuration
app:
  ai:
    enabled: true
  scanner:
    max-file-size-kb: 500
    temp-dir: ${java.io.tmpdir}/repolens
  oci:
    config-file: ./OCI_ApiKey/config
    private-key-file: ./OCI_ApiKey/oracle_santosh.chandrashekar.k-Privatekey.pem

# OCI Configuration
spring:
  ai:
    oci:
      genai:
        compartment-id: ocid1.compartment.oc1..aaaaaaaacqxr3j2qbhntidg2s32gb67lv7ydpbfkvcazqvnjfsaxj3vdxr7a
        endpoint: https://inference.generativeai.us-ashburn-1.oci.oraclecloud.com
        chat:
          enabled: true
          options:
            model: ocid1.generativeaimodel.oc1.iad.amaaaaaask7dceyah6tjdejjashngznsylutuhhvufukzb2g2ls54g2flsfq
            temperature: 0.3
            max-tokens: 2000

# Springdoc OpenAPI
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true

---
spring:
  config:
    activate:
      on-profile: ai

app:
  ai:
    enabled: true
